### ISSUE TITLE
MobaXterm compatibility

### ISSUE THREAD

**Issue by JimboJoe** [IzzySoft/Adebar#23]
Hello,

I needed to have Adebar work under Windows, so I used MobaXterm. It didn't work out-of-the-box, I had to make some small changes in order to make it work:

- use` grep -E` instead of  `egrep`
- small adaptations to the `adb devices` regexp

You'll find the patch here: [Adebar-MobaXterm-Windows.patch.txt](https://github.com/IzzySoft/Adebar/files/721223/Adebar-MobaXterm-Windows.patch.txt)
Here is my hoping to end-up with a unified version, compatible with every platform.
Thanks anyway !

**Comment by IzzySoft** [comment]
Thanks Jimbo – that looks good! I just verified results match with `egrep` vs. `grep -E` on Linux. I could re-check on MobaXterm on Monday (I use that at work where I'm forced to Windows, so I have an environment I know how to deal with) – but I trust it will do; after all it does for you :)

To give credits where credits are due: Maybe you want to fork *Adebar*, apply the changes to your clone, and submit them as pull request – so they are associated with you, and you turn up here as "contributor"?

**Comment by JimboJoe** [comment]
I was mostly concerned by the regexp changes, as I can't test them on Linux (and still can't explain why "$" or "\s" have a different behavior!). I made a proper PR (#24).

**Comment by IzzySoft** [comment]
Thanks, I'll check that.

Must have missed the regex changes on my "quick glance". They might cause misbehavior, especially if a device ID contains a dot or colon, and is separated from the term "device" by spaces instead of a tab – or some error message matches that. The line end mark was omitted, so there could be something like `012.34:5ABC	device has issues`, which would be skipped by the original regex but matched by yours.

What made you change that regex? Can you provide me with the output of `adb devices` on your end? I could then try finding a better solution, and could even test that on MobaXterm on Monday.

**Comment by IzzySoft** [comment]
Thanks again for your contribution! Closing this issue now as it has been solved by your PR #24 :+1:
