### ISSUE TITLE
partBackup: stty not found

### ISSUE THREAD

**Issue by cweiske** [IzzySoft/Adebar#25]
An Samsung Galaxy S5 mini (SM-G800F) with Android 6 does not have the "stty" command used in the partBackup script. The dumped partition data start with:

> sush: stty: not found

A workaround is to use `adb exec-out` instead of `adb shell`, see http://stackoverflow.com/a/39429196/282601

**Comment by IzzySoft** [comment]
Thanks for reporting this and even specifying a work-around! I will check that out ASAP – but at the moment, I'm busy at another project so it will take a little. From a quick glance I take it I probably should replace `stty` by `exec-out` generally, as that's supposed to work on all devices – or should it rather be an option to chose, as devices may exist supporting `stty` but not `exec-out`? I can only test with devices I have, and I don't want to break it for those where it works as-is :stuck_out_tongue_winking_eye:

Pointers: According to [this](https://stackoverflow.com/a/31401447/2533433) and [this](https://stackoverflow.com/a/31917775/2533433) SO posts I'd assume `exec-out` should be generally available. On the other hand, as per [Koush's G+ note](https://plus.google.com/110558071969009568835/posts/Ar3FdhknHo3) it was only added some day in 2014, and thus might not be available for pre-Lollipop devices – which means it should better be an option (with the default set to `exec-out` for LP+ and `stty` otherwise)?

**Comment by cweiske** [comment]
I don't know if that's on adb side or phone side. If on adb side, then it should be safe to simply replace it.

**Comment by IzzySoft** [comment]
I'm not sure either. Guess we simply replace it and wait if someone screams (which I doubt). If, we still can add the check and use it conditionally.

**Comment by IzzySoft** [comment]
@cweiske quick check here shows it should be fine. Feel free to re-open this issue if you think I missed something.

**Comment by cweiske** [comment]
Thanks!
