### ISSUE TITLE
No device found

### ISSUE THREAD

**Issue by nottux** [IzzySoft/Adebar#34]
```
[utku@utku2 Adebar-1.7.0]$ TRANSFER_DIR=/home/utku/Programlar/Adebar-1.7.0/transfers DOCDIR=/home/utku/Programlar/Adebar-1.7.0/doc CACHEDIR=/dev/shm/cache PARTBACKUPDIR=/home/utku/Programlar/Adebar-1.7.0/images SERIAL=4LTS55ZPDICYLNZ5 '/home/utku/Programlar/Adebar-1.7.0/adebar-cli' MK_DEVICEINFO  MK_PARTINFO
No device found. Make sure you have connected your device with
USB debugging enabled, and try again.
```
i already gived adb permissions and i can run adb shell
```
[utku@utku2 Adebar-1.7.0]$ adb shell
VIA_A1:/ $ uname
Linux
VIA_A1:/ $ whoami
shell
VIA_A1:/ $ exit
[utku@utku2 Adebar-1.7.0]$ adb devices
List of devices attached
4LTS55ZPDICYLNZ5	device

[utku@utku2 Adebar-1.7.0]$ 
```
also not working without variables
```
[utku@utku2 Adebar-1.7.0]$ '/home/utku/Programlar/Adebar-1.7.0/adebar-cli' MK_DEVICEINFO  MK_PARTINFO
No device found. Make sure you have connected your device with
USB debugging enabled, and try again.
```

**Comment by nottux** [comment]
in line 166 of the adebar-cli:
```
if [ -z "$(adb devices|grep -E "^[0-9A-Za-z.:]+[[:space:]]+device[[:space:]]*$"|awk '{print $1}')" ]; then
  echo "No device found. Make sure you have connected your device with"
  echo "USB debugging enabled, and try again."
  echo
  exit 2
fi
```

to check if line is faulty i have runned:
```
[utku@utku2 Adebar-1.7.0]$ adb devices|grep -E "^[0-9A-Za-z.:]+[[:space:]]+device[[:space:]]*$"
[utku@utku2 Adebar-1.7.0]$ adb devices|grep -E "[[:space:]]+device[[:space:]]*$"
4LTS55ZPDICYLNZ5	device
[utku@utku2 Adebar-1.7.0]$ 
```
line seems to me faulty

**Comment by IzzySoft** [comment]
$ echo 4LTS55ZPDICYLNZ5  device | grep -E "^[0-9A-Za-z.:]+[[:space:]]+device[[:space:]]*$"
    4LTS55ZPDICYLNZ5 device

So that expression definitely works. Only thing I could imagine is some leading blanks in the output of your `adb devices` – which you could verify by omitting the `^` symbol. If that works, please try another modification:

    $ echo 4LTS55ZPDICYLNZ5  device | grep -E "^[[:space:]]*[0-9A-Za-z.:]+[[:space:]]+device[[:space:]]*$"

which then should "ignore" leading spaces. If that fixes your issue, please let me know so I update the script accordingly.

As you didn't specify any details about your environment (OS, Bash version etc.), I don't know what the culprit could be. Nor do the command lines you gave make any sense to me:

    [utku@utku2 Adebar-1.7.0]$ TRANSFER_DIR=/home/utku/Programlar/Adebar-1.7.0/transfers DOCDIR=/home/utku/Programlar/Adebar-1.7.0/doc CACHEDIR=/dev/shm/cache PARTBACKUPDIR=/home/utku/Programlar/Adebar-1.7.0/images SERIAL=4LTS55ZPDICYLNZ5 '/home/utku/Programlar/Adebar-1.7.0/adebar-cli' MK_DEVICEINFO  MK_PARTINFO

That looks like you try to set variables outside the config – but what shall the two last parameters achieve? Could you try the simple approach first, just calling `adebar-cli` directly? Especially skip the `SERIAL` definition if you only have one device attached anyway (as your `adb shell` and `adb devices` commands suggest).

**Comment by nottux** [comment]
```
[utku@utku2 ~]$ uname -a
Linux utku2 4.16.8-1-ARCH #1 SMP PREEMPT Wed May 9 11:25:02 UTC 2018 x86_64 GNU/Linux
[utku@utku2 ~]$ bash --version
GNU bash, sürüm 4.4.19(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Lisans GPLv3+: GNU GPL sürüm 3 veya sonrası <http://gnu.org/licenses/gpl.html>

Bu ücretsiz bir yazılımdır; değiştirmekte ve dağıtmakta özgürsünüz.
İzin verilen yasalar kapsamında hiçbir GARANTİSİ BULUNMAMAKTADIR.
[utku@utku2 ~]$ 
```
i am using antergos

i understood i shouldn't do this:
```
[utku@utku2 Adebar-1.7.0]$ TRANSFER_DIR=/home/utku/Programlar/Adebar-1.7.0/transfers DOCDIR=/home/utku/Programlar/Adebar-1.7.0/doc CACHEDIR=/dev/shm/cache PARTBACKUPDIR=/home/utku/Programlar/Adebar-1.7.0/images SERIAL=4LTS55ZPDICYLNZ5 '/home/utku/Programlar/Adebar-1.7.0/adebar-cli' MK_DEVICEINFO  MK_PARTINFO
```
then i edited the ``SERIAL=`` to proper serial in file and removed the ``^[0-9A-Za-z.:]+`` in faulty line
it worked just fine :smile:

**Comment by IzzySoft** [comment]
The front part of that command line shouldn't be a problem (though I never tried that). But the two "arguments" won't work.

I've got no idea why the Serial RegEx won't work for you. As I showed, it should work. You didn't check whether my assumption of a possible leading space would cause the issue, so I don't know what I should "correct" (the device ID is needed to check it with the one specified in the config, if any). So unless I know exactly what's happening there, I don't see what I can do and how that line should be "faulty".
