### ISSUE TITLE
Problem with auto-entering backup pw and confirm

### ISSUE THREAD

**Issue by ghost** [IzzySoft/Adebar#39]
Problem / Reproducer
Hi there,
thanks for this wonderful script. Since I've decided to stay unrooted for the moment, I'm using it to backup my apps and data. I've got a problem here, as the auto-confirm config option doesn't work. To reproduce this:
- Use the sample configuration. (Auto confirm is on there)
- Define the var "BACKUP_PASSWORD".
- Run main script with subdir name "_mi8". cd to "_mi8" folder.
- Run "./userbackup" script.
- It shows "Now unlocking your device" and the first package name to backup. The Android device pops up the confirm desktop backup screen from Android and requires me to enter the backup password as I'd previously defined in developer settings.
- Not touching the phone while this is happening:
adb shell input [password] is sent by the desktop and the password appears in the first (from the two password) text fields on the Android screen. 
At the same time: Android keyboard pops up.
PROBLEM: The backup gets stuck here, I have to manually hit the "Backup now" button on the bottom right corner.
EXPECTED: The "Backup now" button is automatically hit by the correct keyevent the desktop has to send to the Android device.

I also found a fix for the problem. Will submit a PR.

Device
Xiaomi Mi8

Android OS
MIUI 10 from Xiaomi, Android 8.1.0 Oreo based.

Desktop OS
Windows 10 Pro x64 using GIT bash based on MinGW.

Maybe related to issue:
#36 "Confirmation on every backup / restore"

**Comment by IzzySoft** [comment]
Thanks for the report and PR, @Catfriend1 – and for confirming my guess concerning #38 (Android 8+). As for the PR, please see the discussion there. Good approach, but needs some fixup to not break other devices :wink: The `sleep` should definitely stay, as some devices seem to need it. If it annoys you: it's a single line in the resulting backup/restore scripts which you can easily remove there.

And yes, related to that other issue as well :wink:

PS: Nice to see it works on Win10 with Git Bash – might want to add that to the documentation. And your device to the list of tested devices (after we fixed the two open issues that is).

**Comment by IzzySoft** [comment]
Fixed with c84081e (pending your confirmation).

**Comment by ghost** [comment]
Thanks for working on this so fast, really, I like your support and the script base of this tool. I'm so sorry to bother you again - should have done the work myself first more precise - but: After multiple times wiping and turning my Mi Phone to manufacturer's default with stock ROM, I discovered that the dialog is behaving differently. To sum up: We require to adjust the routine to those conditions.

Precondition 1)
User has set a desktop backup password in developer settings (like I had it yesterday when starting out with Adebar)
This will cause the backup dialog to have two text fields and the password has to go to field (1). Then we need
>  adb  shell input text "PW" \
    && sleep 1
    adb  shell input keyevent 61; sleep 3
    adb  shell input keyevent 61; sleep 3
    adb  shell input keyevent 61; sleep 3
    adb  shell input keyevent 66; sleep 3

Precondition 2)
User has NOT set a desktop backup password in developer settings, like its the case for me today after the full wipe. (Reason: I cannot set the password because that breaks Xiaomi's local backup tool which somehow depends on ADB Backup having no password ... )
This will cause the backup dialog to have ONE text field and NO password has to be entered. Then we need
>  adb  shell input text "PW" \
    && sleep 1
    adb  shell input keyevent 61; sleep 3
    adb  shell input keyevent 61; sleep 3
    adb  shell input keyevent 66; sleep 3

I will try testing this later on LG. When backup is working again in the code base, I'll also verify restore routines regarding to how many "61"'s we need.

**Comment by IzzySoft** [comment]
Just for confirmation: Is this solved now? Different keycode sequences are now available.

**Comment by ghost** [comment]
I'm testing it these days ... if sth doesn't work, I can adjust the keycode sequences.

**Comment by IzzySoft** [comment]
That's why I suggested making them configurable :wink: If we have a list of working combinations, it would be a good idea placing them in the Wiki for others to profit from. Currently, I've mentioned both (yours and mine) on the configuration page.

OK, I leave it to you then to close this issue when you deem it solved (or else, to add to it). Thanks for your help with this!

**Comment by ghost** [comment]
Let's close this. When I find further sensible improvements, I'll make a new PR. Thanks for your assistance, too :)

**Comment by IzzySoft** [comment]
Alternatively, when you find new keycode sequences, either add them here or feel free to open another issue. Thanks for all your help! I'd never figured those Xiaomi sequences.

**Comment by ghost** [comment]
Currently testing on LG H815 running Android 7.1.2 with the developer-options backup password SET.
Backup requires the following config params:
BACKUP_PASSWORD="PW"
MK_AUTOCONFIRM_SEQUENCE=(61 61 66)

Note: This is lineageos - it display ONE field for password entry.
Note2: I removed all sleeps and it's working fine and fast.

**Comment by IzzySoft** [comment]
Glad to read! Of course you can adjust the sleep variable to your liking (that's why it is a variable) – and nice to hear setting it to `0` works fine for you.

Guess I should think about a separate wiki page for "recommended settings", where we could a.o. collect which sequences work on what device. Could also list on which devices it doesn't work at all, or which devices even support auto unlocking. Basically, this calls for a table with 4 cols: device name, auto-unlock yes/no, sequence 1, sequence 2 (possibly a 5th column for ROM + Android version, though I think that's not needed; rather a comment column, like for your LOS remark in the previous comment). What do you think?

Update: That could go to the [Hints](https://github.com/IzzySoft/Adebar/wiki/Hints) page.

Update2: Done, just follow [the link](https://github.com/IzzySoft/Adebar/wiki/Hints#auto-confirm-keycode-sequences) :wink:
